import os
import subprocess
from pdf2image import convert_from_path
import argparse


TESSERACT_PATH = "C:\\ZSY\\Applications\\tesseract\\tesseract.exe"
INTERMEDIATE_PATH = "./intermediate"

def pdf_to_text(pdf_path, tesseract_path=TESSERACT_PATH, intermediate_path=INTERMEDIATE_PATH):
    pdf_name = os.path.splitext(os.path.basename(pdf_path))[0]
    output_text_file = os.path.join(os.path.dirname(pdf_path), f"_{pdf_name}.txt")

    # Convert PDF pages to images
    os.makedirs(intermediate_path, exist_ok=True)
    images = convert_from_path(pdf_path, output_folder=intermediate_path, dpi=300)

    temp_files = []

    for i, image in enumerate(images):
        temp_img = f"{intermediate_path}/{pdf_name}_page_{i}.png"
        image.save(temp_img, "PNG")
        temp_files.append(temp_img)

        # Run Tesseract on each image and append output to text file
        command = [tesseract_path, temp_img, f"{intermediate_path}/{pdf_name}_page_{i}"]
        subprocess.run(command)

    # Combine all page text into a single output file
    with open(output_text_file, "w", encoding='utf-8') as outfile:
        for i in range(len(temp_files)):
            txt_file = f"{intermediate_path}/{pdf_name}_page_{i}.txt"
            with open(txt_file, "r", encoding='utf-8') as infile:
                outfile.write(infile.read() + "\n")
            os.remove(txt_file)

    # Clean up temporary image files
    for temp_img in temp_files:
        os.remove(temp_img)
    # Remove any intermediate .ppm files generated by pdf2image
    for ppm_file in os.listdir(intermediate_path):
        if ppm_file.endswith(".ppm"):
            os.remove(os.path.join(intermediate_path, ppm_file))

    return output_text_file

def convert_pdf_in_directory(directory, skip_existing=True, tesseract_path=TESSERACT_PATH, intermediate_path=INTERMEDIATE_PATH):
    for file in os.listdir(directory):
        if file.endswith(".pdf"):
            pdf_path = os.path.join(directory, file)
            pdf_name = os.path.splitext(os.path.basename(pdf_path))[0]
            output_text_file = os.path.join(directory, f"_{pdf_name}.txt")
            
            # Check if the output text file already exists
            if os.path.exists(output_text_file) and skip_existing:
                print(f"Skipping {pdf_path} as {output_text_file} already exists.")
                continue
            
            text_file = pdf_to_text(pdf_path, tesseract_path, intermediate_path)
            print(f"Output saved to {text_file}")
    


if __name__ == "__main__":
    # Set up command line argument parsing
    parser = argparse.ArgumentParser(description="Convert PDF to text using OCR.")
    parser.add_argument("pdf_path", help="Path to the PDF file or directory to be converted")
    parser.add_argument("--overwrite", action="store_true", help="Ignore existing output files and overwrite them")
    args = parser.parse_args()

    # If the provided path is a directory, convert all PDFs in the directory
    if os.path.isdir(args.pdf_path):
        convert_pdf_in_directory(args.pdf_path, skip_existing=not args.overwrite)
    else:
        text_file = pdf_to_text(args.pdf_path)
        print(f"Output saved to {text_file}")
